name: RunTests

on:
  push:
    branches-ignore:
      - master
      - release-candidate
      - stage
      - production

jobs:

  test:
    name: Unit + Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run all tests
        env:
          DOCKER_BUILDKIT: '1'
        run: make run_tests

  flake8:
    needs: test
    name: Style code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run flake8
        env:
          DOCKER_BUILDKIT: '1'
        run: pip install -U pip; pip install flake8; flake8 --count .
