name: GitHub Actions create-pull-request
on:
  pull_request:
    types:
      - opened
    branches:
      - 'master'

jobs:

  CreatePatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Patch
        run: |
          git fetch
          git diff ${{ github.base_ref }} ${{ github.head_ref }} > my.patch
          git checkout dev
          git checkout -b lol
          git apply my.patch
          git add .
          git commit -am 'lol_lol'
          git push --set-upstream origin lol

  CreatePullRequest:
    needs: CreatePatch
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: dev
          title: '[Example] Update report'
          base: lol
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-reques
