name: GitHub Actions create-pull-request
on:
  pull_request:
    types:
      - opened
    branches:
      - 'master'

jobs:

  CreatePatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Patch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git fetch
          git diff origin/master origin/f-01 > my.patch
          git checkout dev
          git checkout -b lol
          git apply my.patch
          git add .
          git commit -am 'lol_lol'
          git push --set-upstream origin lol

  CreatePullRequest:
    needs: CreatePatch
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: dev
          PULL_REQUEST_FROM_BRANCH: lol
          PULL_REQUEST_TITLE: This is an auto-generated PR ${{ github.head_ref }} to dev
          PULL_REQUEST_REVIEWERS: ${{ github.actor }}
          PULL_REQUEST_UPDATE: true
